schema_version = "1.0.0"

id = "interfaces_import"
name = "Interfaces Import"
version = "0.4.0"
tagline = "Import interfaces json data to spreadsheet for use with geometry nodes"
type = "add-on"
blender_version_min = "4.2.0"
maintainer = "Lars Bergmann <lars@bergmann82.de>"
tags = ["Import-Export", "Geometry Nodes"]
license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Load JSON files from disk"
